【1.2-常见问题.md】添加.NET Framework 4.8.1下载链接等
MaaAssistantArknights/maa-website pull request #71
Opened 2023-04-07 18:44 UTC by yc080713

添加.NET Framework 4.8.1下载链接
添加 ##连接错误 的解压软件提示

2023-04-08 03:13 UTC, GalvinGao requested changes
修复一下空格和全半角字符的问题

2023-04-08 03:13 UTC, GalvinGao commented on apps/doc/1.2-常见问题.md
> +- 若您是Windows ARM 用户,在安装以上运行库后运行arm64 MAA，弹窗提示 `This application requires one of the following versions of the .NET Farmework: .NET Framework,Version=v4.8.1` ,请安装[.NET Framework 4.8.1](https://dotnet.
```suggestion
- 若您是 Windows ARM 用户，在安装以上运行库后运行 arm64 MAA，弹窗提示 `This application requires one of the following versions of the .NET Farmework: .NET Framework,Version=v4.8.1`，请安装 [.NET Framework 4.8.1](https://dotnet.microsoft.com/zh-cn/download/dotnet-framework/net481)
```

2023-04-08 03:13 UTC, GalvinGao commented on apps/doc/1.2-常见问题.md
> +- 请检查您的解压软件 ———— 部分情况下使用如 `7z` 或 `其他小众解压软件` 会导致 `Minitouch` 相关文件出错
```suggestion
- 请检查您的解压软件 — 部分情况下使用如 `7z` 或 _其他小众解压软件_ 会导致 `Minitouch` 相关文件出错
```

2023-04-08 18:01 UTC, GalvinGao approved these changes

2023-04-08 18:01 UTC, merged

2023-04-09 15:18 UTC, ABA2396 commented
官网的好像打不开1.2了）
![image](https://user-images.githubusercontent.com/99072975/230781255-2d3e3987-fb59-4d0d-859a-1c4c0a5e99f5.png)
![image](https://user-images.githubusercontent.com/99072975/230781263-54185ce5-6379-49cb-9b61-3aea4075bc6f.png)

2023-04-25 04:31 UTC, yc080713 commented
> hmmm可以问一下有关解压软件那部分的提示有可复现案例吗 感觉蛮怪的 7zip也算老牌压缩软件了 不太可能会有这种问题

其实我并没有遇到过这个问题
我经常在用户群里给别人远程，在这个pr提交的几天这个问题特别多
我确定他们使用的是7zip，使用的是解压到当前文件夹选项
解决方法是用文件资源管理器解压，就能让maa正常连接
等还有用户出现这个问题，我会提交issue（不过最近遇到的人很少）

2023-04-25 04:46 UTC, ABA2396 commented
我用的就是7z，应该和这个没啥关系）